# Site settings
title: New Dawn
email: info@newdawnbio.com
url: https://www.newdawnbio.com
description: "The best wood isn't cut. It's cultured."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#282420'
  links: '#8FCC14'

# Footer settings
footer: New Dawn Bio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
